Feat/auth login
vemser/correcao-qa-web pull request #14
Opened 2024-03-02 21:51 UTC by VitorColombo

2024-03-02 21:52 UTC, Luh-Santos requested changes

2024-03-02 21:52 UTC, Luh-Santos commented on src/test/java/com/vemser/correcao/test/funcional/LoginFuncionalTest.java
> +    @Test
Falta tags do Allure

2024-03-02 22:11 UTC, Luh-Santos requested changes

2024-03-02 22:11 UTC, Luh-Santos commented on src/test/java/com/vemser/correcao/test/funcional/LoginFuncionalTest.java
> +    @Severity(SeverityLevel.NORMAL)
Ajustar severidade

2024-03-02 22:11 UTC, Luh-Santos commented on src/test/java/com/vemser/correcao/test/funcional/LoginFuncionalTest.java
> +    @Severity(SeverityLevel.NORMAL)
Ajustar severidade

2024-03-02 22:11 UTC, Luh-Santos commented on src/test/java/com/vemser/correcao/test/funcional/LoginFuncionalTest.java
> +    @Severity(SeverityLevel.NORMAL)
Ajustar severidade

2024-03-02 22:11 UTC, Luh-Santos commented on src/test/java/com/vemser/correcao/test/funcional/LoginFuncionalTest.java
> +    @Severity(SeverityLevel.NORMAL)
Ajustar severidade

2024-03-02 22:11 UTC, Luh-Santos commented on src/test/java/com/vemser/correcao/test/funcional/LoginFuncionalTest.java
> +    @Severity(SeverityLevel.NORMAL)
Ajustar severidade

2024-03-02 22:11 UTC, Luh-Santos commented on src/test/java/com/vemser/correcao/test/funcional/LoginFuncionalTest.java
> +    @Severity(SeverityLevel.NORMAL)
Ajustar severidade

2024-03-03 02:39 UTC, gabrielvendas approved these changes
Tudo certo!

2024-03-03 03:05 UTC, brayanbenet approved these changes

2024-03-03 04:57 UTC, merged